### ISSUE TITLE
Translation Transform is missing the 'two' plural category

### ISSUE THREAD

**Issue by kyleolsondesign** [DockYard/ember-i18n-to-intl-migrator#19]
In the: `translation-transform.js` file, you have a const of the available plural categories:
https://github.com/DockYard/ember-i18n-to-intl-migrator/blob/master/lib/translation-transform.js#L5

But this is missing `'two'`, which is used in Arabic, for example:
https://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#ar

**Comment by snewcomer** [comment]
This should be fixed!  Good call @kyleolsondesign v0.4.0
